name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        python -m pip install git+git://github.com/Ethosa/saya.git
    
    - name: VK demos
      run: |
        cd tests/VK
        for %f in (demo*.py) do python %f
      shell: bash
